### ISSUE TITLE
handle race conditions

### ISSUE THREAD

**Issue by markfisher** [projectriff-demo/trend-detector#2]
see these 3 comments from the original PR:
https://github.com/projectriff-demo/trend-detector/pull/1/files#r355585634
https://github.com/projectriff-demo/trend-detector/pull/1/files#r355584398
https://github.com/projectriff-demo/trend-detector/pull/1/files#r355586077

also:
https://github.com/projectriff-demo/trend-detector/pull/1/files#r355586077

**Comment by fbiville** [comment]
Fixed in b7a25efe761e93c90e9689f8f3af3d4effe892a5
